# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardnum', models.IntegerField(default=1)),
                ('writer', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('contents', models.TextField()),
                ('files', models.FileField(blank=True, upload_to='')),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
