# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddata',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boarddata',
            name='modifydate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boarddata',
            name='boardnum',
            field=models.IntegerField(default=0),
        ),
    ]
